Idle timeout
OpenImaging/miqa-web pull request #12
Opened 2021-06-08 14:47 UTC by venkatabhishek

Fixes OpenImaging/miqa#3

Current approach displays timeout dialog if user has not made any actions (any one of 'mousemove', 'keydown', 'mousedown', or 'touchstart') within **1 hour**.

Timeout dialog will then log the user out (`oauthClient.logout()`) after **5 minutes** if the user does not explicitly press 'continue session'. Dialog displays dynamic timer for this

Dialog also provides action to logout directly, and refresh page after logout.

Uses [idle-vue](https://www.npmjs.com/package/idle-vue) package to detect idle status through events, but this behavior can be re-created if desired

2021-06-08 15:07 UTC, zachmullen commented on client/src/components/TimeoutDialog.vue
> +  padding: 15px 25px !important;
Can we use the vuetify `px-` and `py-` classes here? https://vuetifyjs.com/en/styles/spacing/

2021-06-09 18:35 UTC, dchiquito commented
Some new requirements: https://github.com/OpenImaging/miqa/issues/3#issuecomment-857959522

2021-06-11 19:10 UTC, venkatabhishek commented
As of this commit, implementation satisfies these requirements: https://github.com/OpenImaging/miqa/issues/3#issuecomment-858782587

Notes:
- `settimeout` and `cleartimeout` are used to track actions: When app starts, the timer is started. Whenever an API request is made, the timer is reset. Not sure if having a long running `settimeout` or frequent calls to reset this would result in performance issues.
- Assumption is that oauth access tokens expire in 30 minutes (will make PR for this). The [oauth client library used](https://www.npmjs.com/package/@girder/oauth-client) does not directly expose checking expiration/refreshing token. Instead, this is abstracted into a method `maybeRestoreLogin` which will try to resume the oauth flow in addition to refreshing. As a result, not sure if this will have side effects
- Session exiting dialog is used both for idle user (no mouse clicks/movements) and for no-actions (no API requests)

2021-06-11 21:58 UTC, dchiquito requested changes

2021-06-11 21:58 UTC, dchiquito commented on client/src/django.js
> +      await this.resetActionTimer();
An axios interceptor seems cleaner than having to hard code this in every method here: https://axios-http.com/docs/interceptors

2021-06-11 21:58 UTC, dchiquito commented on client/src/components/TimeoutDialog.vue
> +    isAppIdle(idle) {
I assume this is a magic phrase that vue-idle looks for. Would you mind documenting that here?

2021-06-11 21:58 UTC, dchiquito commented on client/src/components/TimeoutDialog.vue
> +const initSeconds = 59;
The token expires in 30 minutes, the app idle listener triggers at 15 minutes, but the timer dialog starts at 2 minutes. Does this perhaps need to be adjusted, or am I misunderstanding the intended behavior?

2021-06-15 00:51 UTC, venkatabhishek commented on client/src/components/TimeoutDialog.vue
> +    isAppIdle(idle) {
I added it as a comment as well: vue-idle adds a computed value isAppIdle to all Vue objects. This value is shorthand for `store.state.idleVue.isIdle`, i.e. the value that the library attaches to the vuex store to track idle state

2021-06-15 00:58 UTC, venkatabhishek commented on client/src/components/TimeoutDialog.vue
> +const initSeconds = 59;
So here is my understanding: There are two sources of 'idle'-ness. 
- The first form is purely based on interaction: if the user does not click on a button, move the mouse, etc. for **15 minutes**, the idle dialog comes up
- The second for is based on API requests: if the user is still clicking around but not making any actions (such as adding a note, or setting a decision) for **30 minute**, the idle dialog also comes up

In both cases, the idle dialog has a **2 minute** count down timer (after the 15 or 30 minutes above) that logs the user out if they don't click continue session. Whenever the idle timer for type 2 is reset (i.e. an API request is made), it checks if the token is expired and requests a new one if needed. Does this make sense?

2021-06-15 01:01 UTC, venkatabhishek commented on client/src/components/TimeoutDialog.vue
> +const initSeconds = 59;
I guess yes if the token expiration is 30 minutes and the user is idle type 2 for 30 minutes, the token will already be invalidated during the time the idle dialog is being shown, but I'm not sure if this matters because a new token is always requested, the original token is not being extended and re-used

2021-06-17 16:08 UTC, dchiquito commented on client/src/django.js
> +      apiClient.interceptors.request.use(async (config) => {
I think putting this in `restoreLogin` might start stacking extra interceptors if `restoreLogin` is called multiple times. I think it's only called once when the page loads, but I'm not sure.

2021-06-17 16:08 UTC, dchiquito approved these changes

2021-06-17 16:25 UTC, venkatabhishek commented on client/src/django.js
> +      apiClient.interceptors.request.use(async (config) => {
Yes, `restoreLogin` is only ever called once on startup in `main.js`

2021-06-17 16:30 UTC, merged